// PersonalWebsite/src/App.jsx
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Home from './components/Home'
import Projects from './components/Projects'
import Contact from './components/Contact'

import './App.css'

function App() {

	return (
		<>
			<div className ="flex-row">
				<  Navbar  />	
				<	Home   />
				< Projects />
				<  Contact />
				<  Footer  />
			</div>
		</>
	)
}

export default App

// Front-End/personalWebsite-Svelte/src/App.svelte

<script>
	import Contact from "./lib/Contact.svelte";
	import Footer from "./lib/Footer.svelte";
	import Home from "./lib/Home.svelte";
	import Navbar from "./lib/Navbar.svelte";
	import Projects from "./lib/Projects.svelte";

</script>

<main>
	<Navbar />
	<Home />
	<Projects />
	<Contact />
	<Footer />
</main>
