// Front-End/personalWebsite-Svelte/src/lib/Navbar.svelte

<div class='font-mono w-full h-[80px] fixed bg-[#000814] flex justify-between items-center px-4 mb-'>
	<div>
		<h1 class='text-5xl  text-color5 ml-10 '>FM</h1>
	</div>

	<div class="hidden md:inline-flex items-center">
		<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-l">
			Resume
		</button>
		<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4">
			Projects
		</button>
		<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4">
			Contact
		</button>
		<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-r">
			Cool Shit
		</button>
	</div>

	
</div>

// PersonalWebsite/src/components/Navbar.jsx

function Navbar() {


    return (
			<nav className='fixed w-full h-[80px] bg-color2 border-2 border-black flex justify-between items-center px-4 '>
				<div>
					<h1 className='text-5xl font-semibold text-color1 ml-10 '>Filipe Madureira</h1>
				</div>

				<ul className='flex items-center'>
					<li className='mx-2'>
						<a 
							className='bg-color3 border-2 text-xl font-semibold border-black text-black px-5 py-3 rounded-lg' 
							href='#'
							>
							Resume
						</a>
					</li>

					<li className='mx-2'>
						<a 
							className='bg-color4 border-2 text-xl font-semibold border-black text-black py-3 px-5 rounded-lg' 
							href='#'
							>
							Projects
						</a>
					</li>

					<li className='mx-2'>
						<a 
							className='bg-color5 border-2 text-xl font-semibold border-black text-black py-3 px-5 rounded-lg' 
							href='#'
							>
							Contact
						</a>
					</li>
				</ul>
			</nav>
	)
  }
  
  export default Navbar
