// Front-End/personalWebsite-Svelte/src/lib/Projects.svelte
<h1 class='bg-[#001d3d] text-4xl text-center sm:text-7xl font-bold text-[#ccd6f6] pb-10'>
    Projects
</h1>
<div class="bg-[#001d3d] grid lg:grid-cols-3 sm:grid-cols-1 place-items-center">
    <div class="max-w-sm rounded overflow-hidden shadow-lg my-5 mx-5 bg-[#d3d3d3] hover:scale-110 duration-200">
        <img class="w-full" src="./src/assets/NASAWallpaperCard.png" alt="Sunset in the mountains"/>
        <div class="px-6 py-4 ">
            <div class="font-bold text-xl mb-2 text-color1">
                The Coldest Sunset
            </div>
            <p class="text-gray-700 text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
            </p>
        </div>
        <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#photography</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#travel</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#winter</span>
        </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-lg my-5 mx-5 bg-[#d3d3d3] hover:scale-110 duration-200">
        <img class="w-full" src="./src/assets/NASAWallpaperCard.png" alt="Sunset in the mountains"/>
        <div class="px-6 py-4 ">
            <div class="font-bold text-xl mb-2 text-color1">
                The Coldest Sunset
            </div>
            <p class="text-gray-700 text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
            </p>
        </div>
        <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#photography</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#travel</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#winter</span>
        </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden shadow-lg my-5 mx-5 bg-[#d3d3d3] hover:scale-110 duration-200">
        <img class="w-full" src="./src/assets/NASAWallpaperCard.png" alt="Sunset in the mountains"/>
        <div class="px-6 py-4 ">
            <div class="font-bold text-xl mb-2 text-color1">
                The Coldest Sunset
            </div>
            <p class="text-gray-700 text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
            </p>
        </div>
        <div class="px-6 pt-4 pb-2">
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#photography</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#travel</span>
            <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#winter</span>
        </div>
    </div>
</div>

// Front-End/PersonalWebsite/src/components/Projects.jsx
function Projects() {


    return ( 
		<>
			<h1 className='bg-[#001d3d] text-4xl text-center sm:text-7xl font-bold text-[#ccd6f6] pb-10'>
				Projects
			</h1>
			<div className="bg-[#001d3d] grid lg:grid-cols-3 sm:grid-cols-1 place-items-center ">
				{/* Project 1*/}
					<div className="max-w-sm rounded overflow-hidden shadow-lg my-5 mx-5 bg-[#d3d3d3] hover:scale-110 duration-200">

						<img className="w-full" src="./src/assets/NASAWallpaperCard.png" alt="Sunset in the mountains"/>
						<div className="px-6 py-4 ">
							<div className="font-bold text-xl mb-2 text-color1">
								The Coldest Sunset
							</div>
							<p className="text-gray-700 text-base">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
							</p>
						</div>

						<div className="px-6 pt-4 pb-2">
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#photography</span>
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#travel</span>
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#winter</span>
						</div>
					</div>
					<div className="max-w-sm rounded overflow-hidden shadow-lg my-5 mx-5 bg-[#d3d3d3] hover:scale-110 duration-200">

						<img className="w-full" src="./src/assets/NASAWallpaperCard.png" alt="Sunset in the mountains"/>
						<div className="px-6 py-4 ">
							<div className="font-bold text-xl mb-2 text-color1">
								The Coldest Sunset
							</div>
							<p className="text-gray-700 text-base">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
							</p>
						</div>

						<div className="px-6 pt-4 pb-2">
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#photography</span>
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#travel</span>
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#winter</span>
						</div>
					</div>
					<div className="max-w-sm rounded overflow-hidden shadow-lg my-5 mx-5 bg-[#d3d3d3] hover:scale-110 duration-200">

						<img className="w-full" src="./src/assets/NASAWallpaperCard.png" alt="Sunset in the mountains"/>
						<div className="px-6 py-4 ">
							<div className="font-bold text-xl mb-2 text-color1">
								The Coldest Sunset
							</div>
							<p className="text-gray-700 text-base">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
							</p>
						</div>

						<div className="px-6 pt-4 pb-2">
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#photography</span>
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#travel</span>
							<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#winter</span>
						</div>
					</div>
			</div>
		</>
    )
}
  
  export default Projects
